[workspace]
members = [
  "launchpad-common",
  "launchpad",
  "launchpad/meta",
  "launchpad-with-nft",
  "launchpad-with-nft/meta",
  "launchpad-guaranteed-tickets",
  "launchpad-guaranteed-tickets/meta"
]
