[package]
name = "launchpad-v2-meta"
version = "0.0.0"
authors = ["Dorin Iancu <dorin.iancu@elrond.com>"]
edition = "2018"
publish = false

[dependencies.launchpad-v2]
path = ".."

[dependencies.elrond-wasm]
version = "0.31.1"

[dependencies.elrond-wasm-debug]
version = "0.31.1"
