[package]
name = "launchpad"
version = "0.0.0"
authors = ["Dorin Iancu <dorin.iancu@elrond.com>"]
edition = "2018"
publish = false

[lib]
path = "src/launchpad.rs"

[dependencies.elrond-wasm]
version = "0.22.6"

[dev-dependencies.elrond-wasm-debug]
version = "0.22.6"
