[package]
name = "launchpad-common"
version = "0.0.0"
authors = ["Dorin Marian Iancu <dorin.iancu@elrond.com>"]
edition = "2021"

[lib]
path = "src/lib.rs"

[dependencies.multiversx-sc]
version = "0.54.1"

[dependencies.multiversx-sc-modules]
version = "0.54.1"
