[package]
name = "launchpad-common"
version = "0.0.0"
authors = [ "Dorin Marian Iancu <dorin.iancu@elrond.com>",]
edition = "2018"

[lib]
path = "src/lib.rs"

[dependencies.elrond-wasm]
version = "0.31.1"

[dependencies.elrond-wasm-modules]
version = "0.31.1"
