name: CI

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  actions: write
  checks: write
  pull-requests: write

jobs:
  contracts:
    name: Contracts
    uses: ElrondNetwork/elrond-actions/.github/workflows/contracts.yml@use-token-on-checkout
    with:
      rust-toolchain: nightly-2022-03-01
      vmtools-version: v1.4.43
      extra-build-args: --ignore-eei-checks
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}
